name = "DS"
grammar = "ds"
path_suffixes = ["ds"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
tab_size = 2
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
  { start = "(", end = ")", close = true, newline = false },
]
autoclose_before = ";:.,=}])> \n\t"
